### PR TITLE
Update sauce-connect-launcher to 0.13.0

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by lo1tuma** [comment]
Any feedback so far?

**Comment by lo1tuma** [comment]
In the meantime sauche-connect-launcer 0.13.0 was released. I’ve updated the PR to upgrade to 0.13.0 instead of 0.12.0.

**Comment by lo1tuma** [comment]
ping @shawnbot

**Comment by lxanders** [comment]
:+1: for the update - will have to keep my forked version as long as this uses an old sauce connect launcher.

**Comment by lo1tuma** [comment]
Thank you :beers:.

**Comment by lxanders** [comment]
Thanks! :+1:

**Pull request merged**
